<a href="https://colab.research.google.com/github/ArpitaDeshmukh2024/SPPU_DSBDA_Practicals/blob/main/6/DSBDA_Assign6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB

In [ ]:
data = pd.read_csv('Iris.csv')
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
x = data.iloc[:,1:5]
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
y = data.iloc[:,-1]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test ,  y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 0)

**GaussianNB**

imports the GaussianNB class from the naive_bayes module of scikit-learn.

Gaussian Naive Bayes is a probabilistic classifier based on the Bayes' theorem and assumes that features are independent and normally distributed within each class.

The fit method trains the Gaussian Naive Bayes classifier on the training data by estimating the parameters needed for classification. Specifically, it estimates the mean and standard deviation of each feature for each class in the training data.

In [ ]:
model = GaussianNB().fit(x_train , y_train)

In [ ]:
y_pred = model.predict(x_test)
print(y_pred)

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa']


In [ ]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred) * 100
ac

96.66666666666667

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
print(cm)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


**Error Rate for Setosa Class**

In [ ]:
tp = cm[0][0]
fn = cm[0][1] + cm[0][2]
fp = cm[1][0] + cm[2][0]
tn = cm[1][1] + cm[1][2] + cm[2][1] + cm[2][2]

total = tp + fn + fp + tn
print('True Positive : ' , tp)
print('True Negative : ' , tn)
print('False Positive : ' , fp)
print('False Negative : ' , fn)
print('Total : ' , total)

True Positive :  11
True Negative :  19
False Positive :  0
False Negative :  0
Total :  30


In [ ]:
error_rate = (fp + fn) / total
print('Error Rate : ' , error_rate)

Error Rate :  0.0


**Error Rate for Versicolor Class**

In [ ]:
tp = cm[1][1]
fn = cm[1][0] + cm[1][2]
fp = cm[0][1] + cm[2][1]
tn = cm[0][0] + cm[0][2] + cm[2][0] + cm[2][2]

total = tp + fn + fp + tn
print('True Positive : ' , tp)
print('True Negative : ' , tn)
print('False Positive : ' , fp)
print('False Negative : ' , fn)
print('Total : ' , total)

True Positive :  13
True Negative :  16
False Positive :  1
False Negative :  0
Total :  30


In [ ]:
error_rate = (fp + fn) / total
print('Error Rate : ' , error_rate)

Error Rate :  0.03333333333333333


**Error Rate for Virginica Class**


In [ ]:
tp = cm[2][2]
fn = cm[2][1] + cm[2][0]
fp = cm[0][2] + cm[1][2]
tn = cm[0][0] + cm[0][1] + cm[1][0] + cm[1][1]

total = tp + fn + fp + tn
print('True Positive : ' , tp)
print('True Negative : ' , tn)
print('False Positive : ' , fp)
print('False Negative : ' , fn)
print('Total : ' , total)

True Positive :  5
True Negative :  24
False Positive :  0
False Negative :  1
Total :  30


In [ ]:
error_rate = (fp + fn) / total
print('Error Rate : ' , error_rate)

Error Rate :  0.03333333333333333


In [ ]:
from sklearn.metrics import classification_report
print('Classification Report : ')
print(classification_report(y_test , y_pred))

Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.93      1.00      0.96        13
 Iris-virginica       1.00      0.83      0.91         6

       accuracy                           0.97        30
      macro avg       0.98      0.94      0.96        30
   weighted avg       0.97      0.97      0.97        30

