<a href="https://colab.research.google.com/github/ArpitaDeshmukh2024/SPPU_DSBDA_Practicals/blob/main/5/DSBDA_Assign5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


**LogisticRegression()**

Importing LogisticRegression from scikit-learn allows us to utilize logistic regression for classification tasks. This module provides various functionalities for logistic regression, including fitting models to data, making predictions, and evaluating model performance.

**Logistic Regression**

Logistic regression is a statistical method used for binary classification tasks, where the goal is to predict the probability that an instance belongs to one of two classes.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

In [ ]:
data = pd.read_csv('Social_Network_Ads.csv')
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
data.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

**.iloc**: This is a method provided by pandas for selection by position. It is used to select rows and columns by their integer position in the DataFrame.

[:, [2, 3]]: This part of the code is selecting all rows (:) and the columns at positions 2 and 3 ([2, 3]).

**.values**: This attribute returns a NumPy array containing the selected values from the DataFrame.

In [ ]:
x = data.iloc[:,[2,3]].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [ ]:
y = data.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

imports the **train_test_split function** from the **model_selection** module of the scikit-learn library. This function is commonly used to split datasets into random train and test subsets.

**x** = independednt variables(feature values)

**y** = dependent variable(target values)

**test_size** = It specifies the proportion of the dataset to include in the test split. Here, it's set to 0.2, indicating that 20% of the data will be used for testing, while the remaining 80% will be used for training.

**random_state** = It sets the random seed for reproducibility. It ensures that the data splitting is deterministic, meaning that running the code multiple times will produce the same results.

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x , y, test_size = 0.2, random_state = 0)

imports the **StandardScaler** class from the **preprocessing** module of scikit-learn.

 **StandardScaler** = it is a method for standardizing features by removing the mean and scaling to unit variance.

**fit_transform(training_variable)** = This method of the StandardScaler object is called on the training data (x_train). This method computes the mean and standard deviation of each feature in the training set and then standardizes the features based on these statistics. The standardized features are then assigned back to x_train.

**transform(testing_variable)** = This method of the StandardScaler object is called on the testing data (x_test). This method uses the mean and standard deviation computed from the training set to standardize the features of the testing set. It's important to note that the same scaling factors computed on the training set are applied to the testing set to ensure consistency.

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

imports the **LogisticRegression** class from the **linear_model** module of scikit-learn

**classifier** = LogisticRegression()  :   instance of the LogisticRegression class. By default, this creates a logistic regression classifier with certain hyperparameters.

**fit(independent_training_varible , dependent_training_variable)** : This method of the LogisticRegression object is called to train the logistic regression classifier on the training data (x_train and y_train).

This method fits the logistic regression model to the training data by estimating the parameters (coefficients) that best fit the relationship between the input features (x_train) and the target variable (y_train).

After this, the logistic regression classifier (classifier) has been trained on the training data and is ready to make predictions on new data.

In [ ]:
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

LogisticRegression()

**classifier.predict(x_test)**: This line uses the predict method of the trained classifier object to make predictions on the test data (x_test).

The predict method takes the test data as input and returns the predicted class labels for each instance in the test set.

In [ ]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

imports the **confusion_matrix** function from the **metrics** module of scikit-learn.

**Confusion Matrix** = It is a table that summarizes the performance of a classification model on a set of test data.

The confusion_matrix function is called with two arguments:

y_test: The true labels (actual class labels) of the test data.

y_pred: The predicted labels (predicted class labels) of the test data.

This function computes the confusion matrix based on the true and predicted labels.

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix : ')
print(cm)

Confusion Matrix : 
[[57  1]
 [ 5 17]]


imports the **accuracy_score** function from the **metrics** module of scikit-learn.

**Accuracy Score** = It is a measure of the overall correctness of the classifier's predictions.

The accuracy_score function is called with two arguments: y_test and y_pred

This function computes the accuracy score by comparing the true labels with the predicted labels and calculating the proportion of correct predictions.

The calculated accuracy score is then multiplied by 100 to express it as a percentage.

In [ ]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred) * 100
print('Accuracy Score : ')
print(ac)

Accuracy Score : 
92.5


**tp = total positive** : The count of instances where the true class is positive (1) and the classifier predicts positive (1).

**fp = false positive** : The count of instances where the true class is negative (0) but the classifier predicts positive (1).

**fn = false negative** : The count of instances where the true class is positive (1) but the classifier predicts negative (0).

**tn = true negative** : The count of instances where the true class is negative (0) and the classifier predicts negative (0).

**total** =  summing up all these values to calculate the total number of instances in the confusion matrix.

In [ ]:
tp = cm[0][0]
fp = cm[1][0]
fn = cm[0][1]
tn = cm[1][1]
total = tp + fp + fn + tn
print(total)

80


The **error rate** represents the proportion of incorrectly classified instances relative to the total number of instances. It provides a measure of how often the classifier makes mistakes in its predictions.

In [ ]:
error_rate = (fp + fn) / total
print('error rate : ')
print(error_rate)

error rate : 
0.075


imports the **classification_repor**t function from the **metrics** module of scikit-learn.

The classification report provides a summary of various classification metrics, such as precision, recall, F1-score, and support, for each class in the dataset.

The classification_report function is called with two arguments: y_test and y_pred.

Precision: The ratio of true positives to the total number of instances predicted as positive. It measures the ability of the classifier not to label a negative sample as positive.

Recall: The ratio of true positives to the total number of actual positive instances. It measures the ability of the classifier to find all the positive samples.

F1-score: The harmonic mean of precision and recall. It provides a single metric that balances precision and recall.

Support: The number of actual occurrences of each class in the test dataset.

macro avg : It computes the metrics independently for each class and then averages them.

weighted avg : It is used to compute an overall metric that takes into account the contribution of each class, with more emphasis placed on classes with a larger number of instances.

In [ ]:
from sklearn.metrics import classification_report
print('Classification Report : ')
print(classification_report(y_test, y_pred))

Classification Report : 
              precision    recall  f1-score   support

           0       0.92      0.98      0.95        58
           1       0.94      0.77      0.85        22

    accuracy                           0.93        80
   macro avg       0.93      0.88      0.90        80
weighted avg       0.93      0.93      0.92        80

